// 自动生成的数据文件，请勿手动编辑
const PILLS_DATA = [
    {
        "ID": "40001",
        "PillName": "下品筑基丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "10",
        "PillQuality": "1",
        "BaseRate": "0.40",
        "PillBonus": "0.10",
        "FailLifeLossRate": "0.08",
        "FailXiuyiLossRate": "0.20"
    },
    {
        "ID": "40002",
        "PillName": "中品筑基丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "10",
        "PillQuality": "2",
        "BaseRate": "0.40",
        "PillBonus": "0.20",
        "FailLifeLossRate": "0.08",
        "FailXiuyiLossRate": "0.20"
    },
    {
        "ID": "40003",
        "PillName": "上品筑基丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "10",
        "PillQuality": "3",
        "BaseRate": "0.40",
        "PillBonus": "0.30",
        "FailLifeLossRate": "0.08",
        "FailXiuyiLossRate": "0.20"
    },
    {
        "ID": "40011",
        "PillName": "下品金丹丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "20",
        "PillQuality": "1",
        "BaseRate": "0.30",
        "PillBonus": "0.10",
        "FailLifeLossRate": "0.10",
        "FailXiuyiLossRate": "0.25"
    },
    {
        "ID": "40012",
        "PillName": "中品金丹丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "20",
        "PillQuality": "2",
        "BaseRate": "0.30",
        "PillBonus": "0.20",
        "FailLifeLossRate": "0.10",
        "FailXiuyiLossRate": "0.25"
    },
    {
        "ID": "40013",
        "PillName": "上品金丹丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "20",
        "PillQuality": "3",
        "BaseRate": "0.30",
        "PillBonus": "0.30",
        "FailLifeLossRate": "0.10",
        "FailXiuyiLossRate": "0.25"
    },
    {
        "ID": "40021",
        "PillName": "下品元婴丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "30",
        "PillQuality": "1",
        "BaseRate": "0.25",
        "PillBonus": "0.10",
        "FailLifeLossRate": "0.12",
        "FailXiuyiLossRate": "0.30"
    },
    {
        "ID": "40022",
        "PillName": "中品元婴丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "30",
        "PillQuality": "2",
        "BaseRate": "0.25",
        "PillBonus": "0.20",
        "FailLifeLossRate": "0.12",
        "FailXiuyiLossRate": "0.30"
    },
    {
        "ID": "40023",
        "PillName": "上品元婴丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "30",
        "PillQuality": "3",
        "BaseRate": "0.25",
        "PillBonus": "0.30",
        "FailLifeLossRate": "0.12",
        "FailXiuyiLossRate": "0.30"
    },
    {
        "ID": "40031",
        "PillName": "下品化神丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "40",
        "PillQuality": "1",
        "BaseRate": "0.20",
        "PillBonus": "0.10",
        "FailLifeLossRate": "0.14",
        "FailXiuyiLossRate": "0.35"
    },
    {
        "ID": "40032",
        "PillName": "中品化神丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "40",
        "PillQuality": "2",
        "BaseRate": "0.20",
        "PillBonus": "0.20",
        "FailLifeLossRate": "0.14",
        "FailXiuyiLossRate": "0.35"
    },
    {
        "ID": "40033",
        "PillName": "上品化神丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "40",
        "PillQuality": "3",
        "BaseRate": "0.20",
        "PillBonus": "0.30",
        "FailLifeLossRate": "0.14",
        "FailXiuyiLossRate": "0.35"
    },
    {
        "ID": "40041",
        "PillName": "下品炼虚丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "50",
        "PillQuality": "1",
        "BaseRate": "0.15",
        "PillBonus": "0.10",
        "FailLifeLossRate": "0.16",
        "FailXiuyiLossRate": "0.38"
    },
    {
        "ID": "40042",
        "PillName": "中品炼虚丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "50",
        "PillQuality": "2",
        "BaseRate": "0.15",
        "PillBonus": "0.20",
        "FailLifeLossRate": "0.16",
        "FailXiuyiLossRate": "0.38"
    },
    {
        "ID": "40043",
        "PillName": "上品炼虚丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "50",
        "PillQuality": "3",
        "BaseRate": "0.15",
        "PillBonus": "0.30",
        "FailLifeLossRate": "0.16",
        "FailXiuyiLossRate": "0.38"
    },
    {
        "ID": "40051",
        "PillName": "下品合体丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "60",
        "PillQuality": "1",
        "BaseRate": "0.10",
        "PillBonus": "0.10",
        "FailLifeLossRate": "0.18",
        "FailXiuyiLossRate": "0.42"
    },
    {
        "ID": "40052",
        "PillName": "中品合体丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "60",
        "PillQuality": "2",
        "BaseRate": "0.10",
        "PillBonus": "0.20",
        "FailLifeLossRate": "0.18",
        "FailXiuyiLossRate": "0.42"
    },
    {
        "ID": "40053",
        "PillName": "上品合体丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "60",
        "PillQuality": "3",
        "BaseRate": "0.10",
        "PillBonus": "0.30",
        "FailLifeLossRate": "0.18",
        "FailXiuyiLossRate": "0.42"
    },
    {
        "ID": "40061",
        "PillName": "下品大乘丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "70",
        "PillQuality": "1",
        "BaseRate": "0.08",
        "PillBonus": "0.12",
        "FailLifeLossRate": "0.20",
        "FailXiuyiLossRate": "0.45"
    },
    {
        "ID": "40062",
        "PillName": "中品大乘丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "70",
        "PillQuality": "2",
        "BaseRate": "0.08",
        "PillBonus": "0.22",
        "FailLifeLossRate": "0.20",
        "FailXiuyiLossRate": "0.45"
    },
    {
        "ID": "40063",
        "PillName": "上品大乘丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "70",
        "PillQuality": "3",
        "BaseRate": "0.08",
        "PillBonus": "0.32",
        "FailLifeLossRate": "0.20",
        "FailXiuyiLossRate": "0.45"
    },
    {
        "ID": "40071",
        "PillName": "下品渡劫丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "80",
        "PillQuality": "1",
        "BaseRate": "0.05",
        "PillBonus": "0.15",
        "FailLifeLossRate": "0.25",
        "FailXiuyiLossRate": "0.50"
    },
    {
        "ID": "40072",
        "PillName": "中品渡劫丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "80",
        "PillQuality": "2",
        "BaseRate": "0.05",
        "PillBonus": "0.25",
        "FailLifeLossRate": "0.25",
        "FailXiuyiLossRate": "0.50"
    },
    {
        "ID": "40073",
        "PillName": "上品渡劫丹",
        "PillType": "1",
        "EffectType": "",
        "EffectValue": "0",
        "BreakthroughLevel": "80",
        "PillQuality": "3",
        "BaseRate": "0.05",
        "PillBonus": "0.35",
        "FailLifeLossRate": "0.25",
        "FailXiuyiLossRate": "0.50"
    },
    {
        "ID": "40101",
        "PillName": "培元丹",
        "PillType": "2",
        "EffectType": "Xiuyi",
        "EffectValue": "50",
        "BreakthroughLevel": "0",
        "PillQuality": "0",
        "BaseRate": "0",
        "PillBonus": "0",
        "FailLifeLossRate": "0",
        "FailXiuyiLossRate": "0"
    },
    {
        "ID": "40102",
        "PillName": "聚灵丹",
        "PillType": "2",
        "EffectType": "Tipao",
        "EffectValue": "30",
        "BreakthroughLevel": "0",
        "PillQuality": "0",
        "BaseRate": "0",
        "PillBonus": "0",
        "FailLifeLossRate": "0",
        "FailXiuyiLossRate": "0"
    },
    {
        "ID": "40103",
        "PillName": "固本丹",
        "PillType": "2",
        "EffectType": "Life",
        "EffectValue": "10",
        "BreakthroughLevel": "0",
        "PillQuality": "0",
        "BaseRate": "0",
        "PillBonus": "0",
        "FailLifeLossRate": "0",
        "FailXiuyiLossRate": "0"
    }
];

module.exports = PILLS_DATA;
