// 自动生成的数据文件，请勿手动编辑
const RECIPES_DATA = [
    {
        "ID": "1",
        "RecipeName": "下品筑基丹",
        "RecipeDesc": "练气大圆满突破筑基(下品)",
        "ResultItemID": "40001",
        "ResultCount": "1",
        "Material1ID": "20004",
        "Material1Count": "5",
        "Material2ID": "50001",
        "Material2Count": "3",
        "Material3ID": "0",
        "Material3Count": "0"
    },
    {
        "ID": "2",
        "RecipeName": "中品筑基丹",
        "RecipeDesc": "练气大圆满突破筑基(中品)",
        "ResultItemID": "40002",
        "ResultCount": "1",
        "Material1ID": "20004",
        "Material1Count": "10",
        "Material2ID": "50001",
        "Material2Count": "5",
        "Material3ID": "50002",
        "Material3Count": "1"
    },
    {
        "ID": "3",
        "RecipeName": "上品筑基丹",
        "RecipeDesc": "练气大圆满突破筑基(上品)",
        "ResultItemID": "40003",
        "ResultCount": "1",
        "Material1ID": "20004",
        "Material1Count": "18",
        "Material2ID": "50001",
        "Material2Count": "10",
        "Material3ID": "50002",
        "Material3Count": "3"
    },
    {
        "ID": "4",
        "RecipeName": "下品金丹丹",
        "RecipeDesc": "筑基大圆满突破金丹(下品)",
        "ResultItemID": "40011",
        "ResultCount": "1",
        "Material1ID": "20005",
        "Material1Count": "5",
        "Material2ID": "50002",
        "Material2Count": "3",
        "Material3ID": "0",
        "Material3Count": "0"
    },
    {
        "ID": "5",
        "RecipeName": "中品金丹丹",
        "RecipeDesc": "筑基大圆满突破金丹(中品)",
        "ResultItemID": "40012",
        "ResultCount": "1",
        "Material1ID": "20005",
        "Material1Count": "10",
        "Material2ID": "50002",
        "Material2Count": "5",
        "Material3ID": "50003",
        "Material3Count": "1"
    },
    {
        "ID": "6",
        "RecipeName": "上品金丹丹",
        "RecipeDesc": "筑基大圆满突破金丹(上品)",
        "ResultItemID": "40013",
        "ResultCount": "1",
        "Material1ID": "20005",
        "Material1Count": "18",
        "Material2ID": "50002",
        "Material2Count": "10",
        "Material3ID": "50003",
        "Material3Count": "3"
    },
    {
        "ID": "7",
        "RecipeName": "下品元婴丹",
        "RecipeDesc": "金丹大圆满突破元婴(下品)",
        "ResultItemID": "40021",
        "ResultCount": "1",
        "Material1ID": "20006",
        "Material1Count": "5",
        "Material2ID": "50003",
        "Material2Count": "3",
        "Material3ID": "0",
        "Material3Count": "0"
    },
    {
        "ID": "8",
        "RecipeName": "中品元婴丹",
        "RecipeDesc": "金丹大圆满突破元婴(中品)",
        "ResultItemID": "40022",
        "ResultCount": "1",
        "Material1ID": "20006",
        "Material1Count": "10",
        "Material2ID": "50003",
        "Material2Count": "5",
        "Material3ID": "50004",
        "Material3Count": "1"
    },
    {
        "ID": "9",
        "RecipeName": "上品元婴丹",
        "RecipeDesc": "金丹大圆满突破元婴(上品)",
        "ResultItemID": "40023",
        "ResultCount": "1",
        "Material1ID": "20006",
        "Material1Count": "18",
        "Material2ID": "50003",
        "Material2Count": "10",
        "Material3ID": "50004",
        "Material3Count": "3"
    },
    {
        "ID": "10",
        "RecipeName": "下品化神丹",
        "RecipeDesc": "元婴大圆满突破化神(下品)",
        "ResultItemID": "40031",
        "ResultCount": "1",
        "Material1ID": "20007",
        "Material1Count": "5",
        "Material2ID": "50004",
        "Material2Count": "3",
        "Material3ID": "0",
        "Material3Count": "0"
    },
    {
        "ID": "11",
        "RecipeName": "中品化神丹",
        "RecipeDesc": "元婴大圆满突破化神(中品)",
        "ResultItemID": "40032",
        "ResultCount": "1",
        "Material1ID": "20007",
        "Material1Count": "10",
        "Material2ID": "50004",
        "Material2Count": "5",
        "Material3ID": "50005",
        "Material3Count": "1"
    },
    {
        "ID": "12",
        "RecipeName": "上品化神丹",
        "RecipeDesc": "元婴大圆满突破化神(上品)",
        "ResultItemID": "40033",
        "ResultCount": "1",
        "Material1ID": "20007",
        "Material1Count": "18",
        "Material2ID": "50004",
        "Material2Count": "10",
        "Material3ID": "50005",
        "Material3Count": "3"
    },
    {
        "ID": "13",
        "RecipeName": "下品炼虚丹",
        "RecipeDesc": "化神大圆满突破炼虚(下品)",
        "ResultItemID": "40041",
        "ResultCount": "1",
        "Material1ID": "20007",
        "Material1Count": "8",
        "Material2ID": "50004",
        "Material2Count": "4",
        "Material3ID": "50005",
        "Material3Count": "1"
    },
    {
        "ID": "14",
        "RecipeName": "中品炼虚丹",
        "RecipeDesc": "化神大圆满突破炼虚(中品)",
        "ResultItemID": "40042",
        "ResultCount": "1",
        "Material1ID": "20007",
        "Material1Count": "15",
        "Material2ID": "50004",
        "Material2Count": "8",
        "Material3ID": "50005",
        "Material3Count": "3"
    },
    {
        "ID": "15",
        "RecipeName": "上品炼虚丹",
        "RecipeDesc": "化神大圆满突破炼虚(上品)",
        "ResultItemID": "40043",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "5",
        "Material2ID": "50005",
        "Material2Count": "5",
        "Material3ID": "50004",
        "Material3Count": "10"
    },
    {
        "ID": "16",
        "RecipeName": "下品合体丹",
        "RecipeDesc": "炼虚大圆满突破合体(下品)",
        "ResultItemID": "40051",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "5",
        "Material2ID": "50005",
        "Material2Count": "3",
        "Material3ID": "50004",
        "Material3Count": "5"
    },
    {
        "ID": "17",
        "RecipeName": "中品合体丹",
        "RecipeDesc": "炼虚大圆满突破合体(中品)",
        "ResultItemID": "40052",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "10",
        "Material2ID": "50005",
        "Material2Count": "5",
        "Material3ID": "20010",
        "Material3Count": "2"
    },
    {
        "ID": "18",
        "RecipeName": "上品合体丹",
        "RecipeDesc": "炼虚大圆满突破合体(上品)",
        "ResultItemID": "40053",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "18",
        "Material2ID": "50005",
        "Material2Count": "10",
        "Material3ID": "20010",
        "Material3Count": "5"
    },
    {
        "ID": "19",
        "RecipeName": "下品大乘丹",
        "RecipeDesc": "合体大圆满突破大乘(下品)",
        "ResultItemID": "40061",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "10",
        "Material2ID": "50005",
        "Material2Count": "5",
        "Material3ID": "20010",
        "Material3Count": "2"
    },
    {
        "ID": "20",
        "RecipeName": "中品大乘丹",
        "RecipeDesc": "合体大圆满突破大乘(中品)",
        "ResultItemID": "40062",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "18",
        "Material2ID": "50005",
        "Material2Count": "10",
        "Material3ID": "20010",
        "Material3Count": "5"
    },
    {
        "ID": "21",
        "RecipeName": "上品大乘丹",
        "RecipeDesc": "合体大圆满突破大乘(上品)",
        "ResultItemID": "40063",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "30",
        "Material2ID": "50005",
        "Material2Count": "18",
        "Material3ID": "20010",
        "Material3Count": "10"
    },
    {
        "ID": "22",
        "RecipeName": "下品渡劫丹",
        "RecipeDesc": "大乘大圆满突破渡劫(下品)",
        "ResultItemID": "40071",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "18",
        "Material2ID": "50005",
        "Material2Count": "10",
        "Material3ID": "20010",
        "Material3Count": "5"
    },
    {
        "ID": "23",
        "RecipeName": "中品渡劫丹",
        "RecipeDesc": "大乘大圆满突破渡劫(中品)",
        "ResultItemID": "40072",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "30",
        "Material2ID": "50005",
        "Material2Count": "18",
        "Material3ID": "20010",
        "Material3Count": "10"
    },
    {
        "ID": "24",
        "RecipeName": "上品渡劫丹",
        "RecipeDesc": "大乘大圆满突破渡劫(上品)",
        "ResultItemID": "40073",
        "ResultCount": "1",
        "Material1ID": "20008",
        "Material1Count": "45",
        "Material2ID": "50005",
        "Material2Count": "30",
        "Material3ID": "20010",
        "Material3Count": "18"
    },
    {
        "ID": "25",
        "RecipeName": "培元丹",
        "RecipeDesc": "服用后修为+50",
        "ResultItemID": "40101",
        "ResultCount": "3",
        "Material1ID": "20004",
        "Material1Count": "3",
        "Material2ID": "50001",
        "Material2Count": "2",
        "Material3ID": "0",
        "Material3Count": "0"
    },
    {
        "ID": "26",
        "RecipeName": "聚灵丹",
        "RecipeDesc": "服用后体魄+30",
        "ResultItemID": "40102",
        "ResultCount": "2",
        "Material1ID": "20005",
        "Material1Count": "3",
        "Material2ID": "50002",
        "Material2Count": "2",
        "Material3ID": "0",
        "Material3Count": "0"
    },
    {
        "ID": "27",
        "RecipeName": "固本丹",
        "RecipeDesc": "服用后寿命+10",
        "ResultItemID": "40103",
        "ResultCount": "2",
        "Material1ID": "20006",
        "Material1Count": "3",
        "Material2ID": "50003",
        "Material2Count": "2",
        "Material3ID": "0",
        "Material3Count": "0"
    }
];

module.exports = RECIPES_DATA;
