// 自动生成的数据文件，请勿手动编辑
const EVENTS_DATA = [
    {
        "ID": "1",
        "Desc": "你在山间偶遇灵泉，沐浴后神清气爽",
        "Xiuyi": "18",
        "Tipao": "8",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "10000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "2",
        "Desc": "你打坐时感悟天地大道，修为小有所增",
        "Xiuyi": "25",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "10000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "3",
        "Desc": "你误食毒果，身体受损",
        "Xiuyi": "-3",
        "Tipao": "-5",
        "Shouming": "-3",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "10000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "4",
        "Desc": "你路见不平拔刀相助，获得气运加持",
        "Xiuyi": "8",
        "Tipao": "5",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "10000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "5",
        "Desc": "你遭遇心魔侵扰，元神受损",
        "Xiuyi": "-3",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "-5",
        "Weight": "10000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "6",
        "Desc": "你在山洞中发现残破玉简，参悟后小有收获",
        "Xiuyi": "28",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "9000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "7",
        "Desc": "你常年苦练体术，筋骨变得更加坚韧",
        "Xiuyi": "5",
        "Tipao": "18",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "9000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "8",
        "Desc": "你偶遇仙鹤指路，发现一处灵气充裕之地",
        "Xiuyi": "20",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "8",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "9",
        "Desc": "你遭遇山洪暴发，狼狈逃脱",
        "Xiuyi": "-2",
        "Tipao": "-6",
        "Shouming": "-4",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "10",
        "Desc": "你救助受伤灵狐，它赠你一颗灵果",
        "Xiuyi": "12",
        "Tipao": "5",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "20001",
        "ItemCount": "3"
    },
    {
        "ID": "11",
        "Desc": "你静心打坐三日，元神得到滋养",
        "Xiuyi": "8",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "12",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "12",
        "Desc": "你虚度光阴，游山玩水一无所获",
        "Xiuyi": "-2",
        "Tipao": "0",
        "Shouming": "-2",
        "Qiyun": "-2",
        "Yuanshen": "0",
        "Weight": "10000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "13",
        "Desc": "你在集市购得一本功法残卷，修炼后略有进益",
        "Xiuyi": "30",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "14",
        "Desc": "你吞服师父赐予的固本培元丹，寿命有所增加",
        "Xiuyi": "5",
        "Tipao": "8",
        "Shouming": "5",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "15",
        "Desc": "你遭遇妖兽袭击，身受轻伤",
        "Xiuyi": "-5",
        "Tipao": "-5",
        "Shouming": "-3",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "16",
        "Desc": "你发现灵泉之水，洗经伐髓",
        "Xiuyi": "20",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "17",
        "Desc": "你在宗门藏经阁借阅功法，修为精进",
        "Xiuyi": "32",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "18",
        "Desc": "你不小心走火入魔，幸被师兄救下",
        "Xiuyi": "-8",
        "Tipao": "0",
        "Shouming": "-5",
        "Qiyun": "0",
        "Yuanshen": "-5",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "19",
        "Desc": "你采集到一株百年灵草，炼制成丹药服下",
        "Xiuyi": "18",
        "Tipao": "10",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "20",
        "Desc": "你参加宗门弟子切磋，小胜一场",
        "Xiuyi": "22",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10005",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "20001",
        "ItemCount": "5"
    },
    {
        "ID": "21",
        "Desc": "你在溪边垂钓，意外钓到一尾灵鱼，食后精力充沛",
        "Xiuyi": "5",
        "Tipao": "10",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "22",
        "Desc": "你夜间修炼时偶见流星，心有所悟",
        "Xiuyi": "15",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "23",
        "Desc": "你在山中迷路三日，饥寒交迫",
        "Xiuyi": "-3",
        "Tipao": "-3",
        "Shouming": "-3",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "9000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "24",
        "Desc": "你偶遇云游散修，互相交流受益匪浅",
        "Xiuyi": "18",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "5",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "20001",
        "ItemCount": "2"
    },
    {
        "ID": "25",
        "Desc": "你在瀑布下打坐修炼，体魄增强",
        "Xiuyi": "10",
        "Tipao": "20",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "26",
        "Desc": "你被师姐指导剑法，修为精进",
        "Xiuyi": "28",
        "Tipao": "8",
        "Shouming": "0",
        "Qiyun": "3",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "27",
        "Desc": "你发现一处废弃矿洞，从中挖出灵石若干",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "12",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "20001",
        "ItemCount": "8"
    },
    {
        "ID": "28",
        "Desc": "你在林中遭遇毒蛇，中毒后寿命受损",
        "Xiuyi": "0",
        "Tipao": "-3",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "29",
        "Desc": "你帮助村民驱赶妖兽，获得感谢",
        "Xiuyi": "12",
        "Tipao": "8",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "20001",
        "ItemCount": "3"
    },
    {
        "ID": "30",
        "Desc": "你在梦中受高人指点，醒来后若有所悟",
        "Xiuyi": "22",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "31",
        "Desc": "你在深山发现一株千年灵芝，服用后功力大增",
        "Xiuyi": "35",
        "Tipao": "5",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "32",
        "Desc": "你参加宗门大比，发挥出色获得嘉奖",
        "Xiuyi": "30",
        "Tipao": "15",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10005",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "20001",
        "ItemCount": "8"
    },
    {
        "ID": "33",
        "Desc": "你在秘境中历练，获得珍贵药材",
        "Xiuyi": "22",
        "Tipao": "10",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "5",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "34",
        "Desc": "你遭遇雷暴天气，被余威波及",
        "Xiuyi": "-6",
        "Tipao": "-8",
        "Shouming": "-6",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "35",
        "Desc": "你得到师父传授的高级功法，修为大进",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "20001",
        "ItemCount": "5"
    },
    {
        "ID": "36",
        "Desc": "你在拍卖会上购得一件法器",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10010",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "37",
        "Desc": "你结交同门好友，一起修炼进步更快",
        "Xiuyi": "20",
        "Tipao": "10",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "8",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "38",
        "Desc": "你遭遇山贼劫道，虽然脱险但受了伤",
        "Xiuyi": "-5",
        "Tipao": "-6",
        "Shouming": "-4",
        "Qiyun": "-3",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "39",
        "Desc": "你在古战场遗迹中吸收残留灵气",
        "Xiuyi": "28",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "40",
        "Desc": "你偶遇炼丹师，花灵石请其炼制培元丹",
        "Xiuyi": "5",
        "Tipao": "12",
        "Shouming": "8",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "41",
        "Desc": "你发现前辈留下的洞府，获得一些修炼资源",
        "Xiuyi": "30",
        "Tipao": "8",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "5",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "20001",
        "ItemCount": "10"
    },
    {
        "ID": "42",
        "Desc": "你在宗门试炼中表现优异，获得奖励",
        "Xiuyi": "35",
        "Tipao": "18",
        "Shouming": "0",
        "Qiyun": "12",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10015",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "20001",
        "ItemCount": "12"
    },
    {
        "ID": "43",
        "Desc": "你遭遇妖兽围攻，苦战后脱身",
        "Xiuyi": "-10",
        "Tipao": "-10",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "44",
        "Desc": "你参悟一部上古功法，修为大增",
        "Xiuyi": "45",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "12",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "45",
        "Desc": "你被长老赏识，获得单独指点",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "46",
        "Desc": "你在秘境中发现灵矿，获得大量灵石",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "20001",
        "ItemCount": "18"
    },
    {
        "ID": "47",
        "Desc": "你遭遇心魔试炼，艰难渡过",
        "Xiuyi": "-6",
        "Tipao": "0",
        "Shouming": "-3",
        "Qiyun": "5",
        "Yuanshen": "15",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "48",
        "Desc": "你与魔修交手，险胜后获得战利品",
        "Xiuyi": "28",
        "Tipao": "18",
        "Shouming": "-5",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "4500",
        "EquipmentID": "10020",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "20001",
        "ItemCount": "10"
    },
    {
        "ID": "49",
        "Desc": "你在幽深洞窟中发现一池灵液",
        "Xiuyi": "22",
        "Tipao": "12",
        "Shouming": "3",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "50",
        "Desc": "你修炼失误，灵力暴走",
        "Xiuyi": "-12",
        "Tipao": "-6",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "-6",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "51",
        "Desc": "你被天雷击中，奇迹般地活了下来",
        "Xiuyi": "15",
        "Tipao": "25",
        "Shouming": "-5",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "52",
        "Desc": "你在废墟中发现一柄古剑，隐含剑意",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "15",
        "Weight": "4500",
        "EquipmentID": "10025",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "53",
        "Desc": "你得到一瓶金丹期修士炼制的灵丹",
        "Xiuyi": "35",
        "Tipao": "0",
        "Shouming": "6",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "54",
        "Desc": "你在山中遭遇暴风雪，体魄受损",
        "Xiuyi": "-3",
        "Tipao": "-8",
        "Shouming": "-6",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "55",
        "Desc": "你结识一位炼器师，获赠法器",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "4500",
        "EquipmentID": "10030",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "56",
        "Desc": "你发现上古传送阵，意外来到一处福地",
        "Xiuyi": "40",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "57",
        "Desc": "你在宗门秘境中获得大量资源",
        "Xiuyi": "35",
        "Tipao": "18",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "20001",
        "ItemCount": "15"
    },
    {
        "ID": "58",
        "Desc": "你遭遇化形妖兽，险死还生",
        "Xiuyi": "-15",
        "Tipao": "-12",
        "Shouming": "-12",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "59",
        "Desc": "你得到前辈遗留的修炼心得，受益良多",
        "Xiuyi": "45",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "60",
        "Desc": "你在闭关中有所突破，道心更坚",
        "Xiuyi": "28",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "61",
        "Desc": "你参加修士聚会，与人论道受益匪浅",
        "Xiuyi": "22",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "12",
        "Yuanshen": "12",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "62",
        "Desc": "你遭遇劫匪，损失惨重",
        "Xiuyi": "-8",
        "Tipao": "0",
        "Shouming": "-5",
        "Qiyun": "-10",
        "Yuanshen": "0",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "63",
        "Desc": "你在密林深处发现一颗万年灵果",
        "Xiuyi": "5",
        "Tipao": "18",
        "Shouming": "10",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "64",
        "Desc": "你与同门师兄比试，惜败但收获颇多",
        "Xiuyi": "15",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "10",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "65",
        "Desc": "你在古墓中发现上古修士遗骸，获得传承玉简",
        "Xiuyi": "50",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "21",
        "ItemID": "20001",
        "ItemCount": "25"
    },
    {
        "ID": "66",
        "Desc": "你炼制丹药失败，灵材尽毁",
        "Xiuyi": "0",
        "Tipao": "0",
        "Shouming": "-3",
        "Qiyun": "-10",
        "Yuanshen": "0",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "67",
        "Desc": "你在天坑底部发现一眼地火，借此淬炼肉身",
        "Xiuyi": "5",
        "Tipao": "30",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "68",
        "Desc": "你遭遇同门暗算，受伤后被发现并救治",
        "Xiuyi": "-10",
        "Tipao": "-6",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "-6",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "69",
        "Desc": "你在商会购得一本绝版功法",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "70",
        "Desc": "你偶遇上古阵法，参悟后神识大增",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "25",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "21",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "71",
        "Desc": "你在仙人遗迹发现一汪仙泉，饮后修为大增",
        "Xiuyi": "55",
        "Tipao": "0",
        "Shouming": "8",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "72",
        "Desc": "你与元婴修士切磋，虽败犹荣",
        "Xiuyi": "20",
        "Tipao": "25",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "73",
        "Desc": "你遭遇天劫余威，身心俱损",
        "Xiuyi": "-15",
        "Tipao": "-10",
        "Shouming": "-12",
        "Qiyun": "0",
        "Yuanshen": "-6",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "74",
        "Desc": "你得到一块天外陨铁，蕴含奇异能量",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "20",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "75",
        "Desc": "你在极北冰原发现太古冰蚕，获得其蚕丝",
        "Xiuyi": "15",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "0",
        "Weight": "3000",
        "EquipmentID": "10035",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "76",
        "Desc": "你参加仙门联合大比，名列前茅",
        "Xiuyi": "45",
        "Tipao": "25",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "3000",
        "EquipmentID": "10040",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "20001",
        "ItemCount": "20"
    },
    {
        "ID": "77",
        "Desc": "你被魔修暗算，险些殒命",
        "Xiuyi": "-18",
        "Tipao": "-15",
        "Shouming": "-15",
        "Qiyun": "0",
        "Yuanshen": "-8",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "78",
        "Desc": "你发现一处龙脉灵眼，在此修炼事半功倍",
        "Xiuyi": "50",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "10",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "79",
        "Desc": "你在深海遗迹中发现上古法宝",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "2500",
        "EquipmentID": "10045",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "80",
        "Desc": "你闭关修炼有成，道行精进",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "81",
        "Desc": "你遭遇天地异变，灵气暴动",
        "Xiuyi": "-10",
        "Tipao": "0",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "-10",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "82",
        "Desc": "你在梦境中经历一世轮回，心境大涨",
        "Xiuyi": "8",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "30",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "83",
        "Desc": "你偶遇仙人分身，获得指点",
        "Xiuyi": "60",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "84",
        "Desc": "你在仙界裂缝处吸收仙灵之气",
        "Xiuyi": "55",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "85",
        "Desc": "你遭遇化神期魔修伏击，浴血苦战",
        "Xiuyi": "-15",
        "Tipao": "-15",
        "Shouming": "-12",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "86",
        "Desc": "你在上古遗迹中获得一枚道果",
        "Xiuyi": "45",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "25",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "87",
        "Desc": "你参加宗门护山大阵演练，获得奖赏",
        "Xiuyi": "35",
        "Tipao": "18",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "10",
        "Weight": "3000",
        "EquipmentID": "10050",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "20001",
        "ItemCount": "25"
    },
    {
        "ID": "88",
        "Desc": "你在雷池中淬炼肉身，脱胎换骨",
        "Xiuyi": "15",
        "Tipao": "35",
        "Shouming": "-5",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "89",
        "Desc": "你遭遇内魔外魔齐攻，元神重创",
        "Xiuyi": "-8",
        "Tipao": "0",
        "Shouming": "-5",
        "Qiyun": "0",
        "Yuanshen": "-18",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "90",
        "Desc": "你在秘境中得到太古神兽精血",
        "Xiuyi": "5",
        "Tipao": "30",
        "Shouming": "8",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "91",
        "Desc": "你参悟天道法则一隅，修为暴涨",
        "Xiuyi": "65",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "92",
        "Desc": "你被困幻阵三年，虽脱困但耗费大量寿元",
        "Xiuyi": "-3",
        "Tipao": "0",
        "Shouming": "-20",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "93",
        "Desc": "你在仙草园中发现九转仙草",
        "Xiuyi": "50",
        "Tipao": "0",
        "Shouming": "12",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "94",
        "Desc": "你遭遇虚空风暴，灵力溃散",
        "Xiuyi": "-20",
        "Tipao": "-8",
        "Shouming": "-10",
        "Qiyun": "0",
        "Yuanshen": "-10",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "95",
        "Desc": "你得到一枚远古仙丹，服用后脱胎换骨",
        "Xiuyi": "60",
        "Tipao": "25",
        "Shouming": "10",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "20001",
        "ItemCount": "35"
    },
    {
        "ID": "96",
        "Desc": "你在仙界边境历练，收获颇丰",
        "Xiuyi": "50",
        "Tipao": "18",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "15",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "20001",
        "ItemCount": "30"
    },
    {
        "ID": "97",
        "Desc": "你遭遇大乘修士降维打击，几乎陨落",
        "Xiuyi": "-22",
        "Tipao": "-18",
        "Shouming": "-18",
        "Qiyun": "0",
        "Yuanshen": "-10",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "98",
        "Desc": "你在混沌之地感悟大道",
        "Xiuyi": "70",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "25",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "99",
        "Desc": "你获得一缕仙界本源之力",
        "Xiuyi": "55",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "15",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "100",
        "Desc": "你在古战场中吸收残留的仙力",
        "Xiuyi": "45",
        "Tipao": "25",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "101",
        "Desc": "你遭遇反噬，修为受损",
        "Xiuyi": "-18",
        "Tipao": "0",
        "Shouming": "-10",
        "Qiyun": "0",
        "Yuanshen": "-15",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "102",
        "Desc": "你在雷劫中悟道，实力大增",
        "Xiuyi": "65",
        "Tipao": "18",
        "Shouming": "-10",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "103",
        "Desc": "你发现一处仙人府邸，获得传承",
        "Xiuyi": "60",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "15",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "20001",
        "ItemCount": "40"
    },
    {
        "ID": "104",
        "Desc": "你在虚空裂缝中发现异宝",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10055",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "105",
        "Desc": "你感悟岁月法则，寿命大增",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "15",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "106",
        "Desc": "你在时间长河中体悟道韵",
        "Xiuyi": "30",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "30",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "107",
        "Desc": "你在远古圣地修炼，功力精进",
        "Xiuyi": "65",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "108",
        "Desc": "你得到仙界赐福，全属性提升",
        "Xiuyi": "40",
        "Tipao": "25",
        "Shouming": "8",
        "Qiyun": "15",
        "Yuanshen": "15",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "20001",
        "ItemCount": "35"
    },
    {
        "ID": "109",
        "Desc": "你遭遇天道雷劫，全身伤痕累累",
        "Xiuyi": "-22",
        "Tipao": "-18",
        "Shouming": "-18",
        "Qiyun": "-8",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "110",
        "Desc": "你参悟空间法则，修为大涨",
        "Xiuyi": "75",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "25",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "111",
        "Desc": "你在仙魔战场获得仙器碎片",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "1500",
        "EquipmentID": "10060",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "112",
        "Desc": "你被仙界高人渡过一缕仙元",
        "Xiuyi": "60",
        "Tipao": "0",
        "Shouming": "10",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "113",
        "Desc": "你遭遇天罚，险些形神俱灭",
        "Xiuyi": "-25",
        "Tipao": "-15",
        "Shouming": "-22",
        "Qiyun": "0",
        "Yuanshen": "-15",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "114",
        "Desc": "你在绝地逢生，心境圆满",
        "Xiuyi": "25",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "35",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "115",
        "Desc": "你在混沌虚空中发现先天至宝",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "25",
        "Yuanshen": "0",
        "Weight": "1000",
        "EquipmentID": "10065",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "116",
        "Desc": "你遭遇仙界追杀，寿命大损",
        "Xiuyi": "-8",
        "Tipao": "0",
        "Shouming": "-25",
        "Qiyun": "-8",
        "Yuanshen": "0",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "117",
        "Desc": "你在世界树下悟道七七四十九天",
        "Xiuyi": "80",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "30",
        "Weight": "1000",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "118",
        "Desc": "你得到创世之力的洗礼",
        "Xiuyi": "70",
        "Tipao": "35",
        "Shouming": "15",
        "Qiyun": "20",
        "Yuanshen": "20",
        "Weight": "1200",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "20001",
        "ItemCount": "55"
    },
    {
        "ID": "119",
        "Desc": "你遭遇天道轮回，前世记忆涌现",
        "Xiuyi": "50",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "30",
        "Yuanshen": "35",
        "Weight": "1200",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "120",
        "Desc": "你在星辰大海中采集星辰之力",
        "Xiuyi": "65",
        "Tipao": "25",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "15",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "20001",
        "ItemCount": "45"
    },
    {
        "ID": "121",
        "Desc": "你遭遇末法天劫，法力尽失后重聚",
        "Xiuyi": "-30",
        "Tipao": "-15",
        "Shouming": "-25",
        "Qiyun": "0",
        "Yuanshen": "-18",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "122",
        "Desc": "你参悟因果法则，道行圆满",
        "Xiuyi": "60",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "40",
        "Weight": "1000",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "123",
        "Desc": "你在永恒之树下获得不朽之力",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "20",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "1000",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "124",
        "Desc": "你遭遇虚空乱流，肉身崩碎后重塑",
        "Xiuyi": "-15",
        "Tipao": "-22",
        "Shouming": "-18",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "1200",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "125",
        "Desc": "你在万界通道中获得至宝",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "30",
        "Yuanshen": "0",
        "Weight": "1000",
        "EquipmentID": "10070",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "126",
        "Desc": "你感悟生死轮回，超脱凡尘",
        "Xiuyi": "55",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "25",
        "Yuanshen": "25",
        "Weight": "1000",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "127",
        "Desc": "你在太虚中发现鸿蒙之气",
        "Xiuyi": "85",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "800",
        "EquipmentID": "10001",
        "LevelMin": "34",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "128",
        "Desc": "你与天道共鸣，修为暴涨",
        "Xiuyi": "90",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "30",
        "Weight": "800",
        "EquipmentID": "10001",
        "LevelMin": "34",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "129",
        "Desc": "你遭遇成仙劫难，全力以赴",
        "Xiuyi": "-40",
        "Tipao": "-22",
        "Shouming": "-30",
        "Qiyun": "0",
        "Yuanshen": "-15",
        "Weight": "1000",
        "EquipmentID": "10001",
        "LevelMin": "38",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "130",
        "Desc": "你在仙界留下道统，功德加身",
        "Xiuyi": "70",
        "Tipao": "30",
        "Shouming": "12",
        "Qiyun": "25",
        "Yuanshen": "25",
        "Weight": "800",
        "EquipmentID": "10001",
        "LevelMin": "38",
        "LevelMax": "42",
        "ItemID": "20001",
        "ItemCount": "65"
    },
    {
        "ID": "131",
        "Desc": "你飞升仙界，成就仙道",
        "Xiuyi": "1000",
        "Tipao": "500",
        "Shouming": "500",
        "Qiyun": "500",
        "Yuanshen": "500",
        "Weight": "1000",
        "EquipmentID": "10001",
        "LevelMin": "42",
        "LevelMax": "42",
        "ItemID": "20001",
        "ItemCount": "100"
    },
    {
        "ID": "132",
        "Desc": "你在野外发现一窝灵蛋，孵化出灵宠",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "12",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "133",
        "Desc": "你被师妹强拉去逛街，耽误了修炼",
        "Xiuyi": "-2",
        "Tipao": "0",
        "Shouming": "-1",
        "Qiyun": "5",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "134",
        "Desc": "你在河底发现一块通灵玉髓",
        "Xiuyi": "15",
        "Tipao": "8",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "135",
        "Desc": "你参加宗门年终考核，获得灵石奖励",
        "Xiuyi": "20",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "20001",
        "ItemCount": "5"
    },
    {
        "ID": "136",
        "Desc": "你在山间遇到雷暴，被劈得外焦里嫩",
        "Xiuyi": "-1",
        "Tipao": "-5",
        "Shouming": "-4",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "137",
        "Desc": "你偷偷跑去看师姐练剑，被师父罚面壁",
        "Xiuyi": "-3",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "-2",
        "Yuanshen": "3",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "138",
        "Desc": "你在井底发现一枚古钱，蕴含奇异灵力",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "5",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "139",
        "Desc": "你吃了师兄炼制的实验性丹药，效果奇特",
        "Xiuyi": "12",
        "Tipao": "-2",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "140",
        "Desc": "你在月圆之夜吸收月华，元神凝实",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "141",
        "Desc": "你下山除妖，斩杀一只百年妖狼",
        "Xiuyi": "18",
        "Tipao": "10",
        "Shouming": "-2",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "142",
        "Desc": "你在枯井中发现上古符文，参悟后有所领悟",
        "Xiuyi": "22",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "143",
        "Desc": "你帮厨房师叔熬制灵汤，偷喝一碗后体魄增强",
        "Xiuyi": "5",
        "Tipao": "15",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "144",
        "Desc": "你在宗门布告栏接了一个除虫任务，轻松完成",
        "Xiuyi": "10",
        "Tipao": "5",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "145",
        "Desc": "你被执法堂罚了三天禁闭，修炼了三天",
        "Xiuyi": "15",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "-3",
        "Yuanshen": "5",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "146",
        "Desc": "你在山涧发现一条灵蛇蜕下的皮，炼制成护身符",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10010",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "147",
        "Desc": "你遭遇暴雨山洪，冲走了你的灵石存款",
        "Xiuyi": "0",
        "Tipao": "0",
        "Shouming": "-2",
        "Qiyun": "-6",
        "Yuanshen": "0",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "148",
        "Desc": "你在梦中游历太虚，与先贤对话",
        "Xiuyi": "15",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "12",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "149",
        "Desc": "你发现一处被遗忘的灵脉矿区",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "18",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "20001",
        "ItemCount": "10"
    },
    {
        "ID": "150",
        "Desc": "你在集市上购得一枚品质不错的丹药",
        "Xiuyi": "22",
        "Tipao": "0",
        "Shouming": "3",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "151",
        "Desc": "你遭遇外门弟子挑衅，将其击败",
        "Xiuyi": "15",
        "Tipao": "10",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "152",
        "Desc": "你在宗门任务中发现了一处秘境入口",
        "Xiuyi": "28",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "5",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "153",
        "Desc": "你参加炼丹大会，获得第三名",
        "Xiuyi": "15",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "5",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "154",
        "Desc": "你遭遇邪修偷袭，虽然击退但消耗巨大",
        "Xiuyi": "-6",
        "Tipao": "-3",
        "Shouming": "-5",
        "Qiyun": "0",
        "Yuanshen": "-3",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "155",
        "Desc": "你在万妖山脉猎杀妖兽，获得兽核若干",
        "Xiuyi": "22",
        "Tipao": "15",
        "Shouming": "-2",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "20001",
        "ItemCount": "12"
    },
    {
        "ID": "156",
        "Desc": "你在悬崖绝壁采得一株断肠草，炼制成续命丹",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "8",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "157",
        "Desc": "你被困在阵法中七日，艰难破阵而出",
        "Xiuyi": "12",
        "Tipao": "0",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "12",
        "Weight": "4500",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "158",
        "Desc": "你在深潭底部发现远古修士的储物袋",
        "Xiuyi": "28",
        "Tipao": "8",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "3500",
        "EquipmentID": "10020",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "20001",
        "ItemCount": "18"
    },
    {
        "ID": "159",
        "Desc": "你被魔修追杀，逃入绝地后意外获得机缘",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "160",
        "Desc": "你在雷泽中历练，肉身得到淬炼",
        "Xiuyi": "15",
        "Tipao": "25",
        "Shouming": "-5",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "161",
        "Desc": "你与道侣双修，功力互补精进",
        "Xiuyi": "32",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "15",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "162",
        "Desc": "你在血池中浸泡三日，体魄脱胎换骨",
        "Xiuyi": "5",
        "Tipao": "35",
        "Shouming": "-3",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "163",
        "Desc": "你感悟四季轮回，道心升华",
        "Xiuyi": "28",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "164",
        "Desc": "你被困在迷雾森林中半月，消耗大量灵力",
        "Xiuyi": "-10",
        "Tipao": "-3",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "165",
        "Desc": "你在火山口采集到地心火莲",
        "Xiuyi": "32",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "10",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "166",
        "Desc": "你在紫霄宫遗址参悟壁画上的仙诀",
        "Xiuyi": "50",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "167",
        "Desc": "你遭遇空间乱流，被卷入异域",
        "Xiuyi": "18",
        "Tipao": "12",
        "Shouming": "-15",
        "Qiyun": "20",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "168",
        "Desc": "你在九天雷池中淬炼元神",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "-8",
        "Qiyun": "0",
        "Yuanshen": "35",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "169",
        "Desc": "你在万界商会拍得一件上古遗物",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "0",
        "Weight": "1500",
        "EquipmentID": "10055",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "170",
        "Desc": "你参悟长生法则，寿命暴增",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "18",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "171",
        "Desc": "你在天地大劫中坚守本心",
        "Xiuyi": "45",
        "Tipao": "12",
        "Shouming": "-5",
        "Qiyun": "10",
        "Yuanshen": "20",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "172",
        "Desc": "你获得一缕天道意志的认可",
        "Xiuyi": "60",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "20",
        "Weight": "1200",
        "EquipmentID": "10001",
        "LevelMin": "30",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "173",
        "Desc": "你在渡劫池中吞吐雷霆",
        "Xiuyi": "55",
        "Tipao": "30",
        "Shouming": "-15",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "1200",
        "EquipmentID": "10001",
        "LevelMin": "34",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "174",
        "Desc": "你在轮回中体验百世人生，道心如铁",
        "Xiuyi": "40",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "35",
        "Weight": "800",
        "EquipmentID": "10001",
        "LevelMin": "38",
        "LevelMax": "42",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "175",
        "Desc": "你下山历练时误入凡间小镇，帮人看病获报酬",
        "Xiuyi": "8",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "8000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "9",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "176",
        "Desc": "你在暴风雨中感悟天地之威",
        "Xiuyi": "15",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "8",
        "Weight": "7000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "177",
        "Desc": "你采药途中发现一株紫灵芝，服用后真气充盈",
        "Xiuyi": "25",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "6000",
        "EquipmentID": "10001",
        "LevelMin": "1",
        "LevelMax": "13",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "178",
        "Desc": "你在坊市与人打赌斗法，赢得一件灵器",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "12",
        "Yuanshen": "0",
        "Weight": "5000",
        "EquipmentID": "10015",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "179",
        "Desc": "你在地底暗河中发现灵石矿脉",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "0",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "21",
        "ItemID": "20001",
        "ItemCount": "15"
    },
    {
        "ID": "180",
        "Desc": "你在飞瀑之下修炼铁布衫神功",
        "Xiuyi": "5",
        "Tipao": "25",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "5",
        "Weight": "5000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "181",
        "Desc": "你在魔渊边缘吸收一丝魔气，炼化后实力大增",
        "Xiuyi": "32",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "10",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "182",
        "Desc": "你在仙魔古战场拾得一片仙甲残片",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10050",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "183",
        "Desc": "你在通天河捕获一条千年锦鲤，食其肉增寿",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "12",
        "Qiyun": "8",
        "Yuanshen": "0",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "184",
        "Desc": "你在死亡沙漠中发现绿洲秘境",
        "Xiuyi": "38",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "10",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "185",
        "Desc": "你在宗门大殿听太上长老讲道一日",
        "Xiuyi": "45",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "15",
        "Weight": "3500",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "186",
        "Desc": "你在虫谷采集到金蚕蛊毒",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "0",
        "Weight": "4000",
        "EquipmentID": "10025",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "187",
        "Desc": "你在雪山之巅打坐七日，心如止水",
        "Xiuyi": "20",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "18",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "188",
        "Desc": "你在鬼域边界感悟死气，对生死有了更深领悟",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "2500",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "189",
        "Desc": "你在仙人遗留的棋局中悟道",
        "Xiuyi": "30",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "25",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "190",
        "Desc": "你在药王谷学习炼丹之术，顺带服了几炉丹药",
        "Xiuyi": "22",
        "Tipao": "8",
        "Shouming": "3",
        "Qiyun": "5",
        "Yuanshen": "5",
        "Weight": "4000",
        "EquipmentID": "10001",
        "LevelMin": "10",
        "LevelMax": "17",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "191",
        "Desc": "你在五行山中感悟五行法则",
        "Xiuyi": "28",
        "Tipao": "12",
        "Shouming": "0",
        "Qiyun": "5",
        "Yuanshen": "10",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "192",
        "Desc": "你遭遇天魔幻境考验，心志坚定通过",
        "Xiuyi": "-3",
        "Tipao": "0",
        "Shouming": "-3",
        "Qiyun": "10",
        "Yuanshen": "15",
        "Weight": "3000",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "193",
        "Desc": "你在古仙洞府发现一面照妖镜",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10040",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "194",
        "Desc": "你在万兽山猎杀妖王，获得妖丹",
        "Xiuyi": "32",
        "Tipao": "25",
        "Shouming": "-5",
        "Qiyun": "15",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10001",
        "LevelMin": "18",
        "LevelMax": "29",
        "ItemID": "20001",
        "ItemCount": "25"
    },
    {
        "ID": "195",
        "Desc": "你在无尽海域中寻到龙宫遗址",
        "Xiuyi": "45",
        "Tipao": "18",
        "Shouming": "0",
        "Qiyun": "20",
        "Yuanshen": "10",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "20001",
        "ItemCount": "30"
    },
    {
        "ID": "196",
        "Desc": "你在时空裂缝中捡到一块混沌石",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "25",
        "Yuanshen": "15",
        "Weight": "1200",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "197",
        "Desc": "你将三千烦恼尽斩，道心通明",
        "Xiuyi": "12",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "30",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "198",
        "Desc": "你在天雷中淬炼法宝，法宝品质提升",
        "Xiuyi": "5",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "10",
        "Yuanshen": "0",
        "Weight": "2000",
        "EquipmentID": "10045",
        "LevelMin": "14",
        "LevelMax": "25",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "199",
        "Desc": "你在梦境中经历轮回，悟得因果之道",
        "Xiuyi": "25",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "15",
        "Yuanshen": "20",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "22",
        "LevelMax": "33",
        "ItemID": "",
        "ItemCount": ""
    },
    {
        "ID": "200",
        "Desc": "你在太古遗迹发现一座传功石碑",
        "Xiuyi": "55",
        "Tipao": "0",
        "Shouming": "0",
        "Qiyun": "0",
        "Yuanshen": "20",
        "Weight": "1500",
        "EquipmentID": "10001",
        "LevelMin": "26",
        "LevelMax": "37",
        "ItemID": "",
        "ItemCount": ""
    }
];

module.exports = EVENTS_DATA;
