// 自动生成的数据文件，请勿手动编辑
const SHOP_DATA = [
    {
        "ID": "1",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20004",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "3000",
        "Price": "5",
        "PriceCurrency": "20001"
    },
    {
        "ID": "2",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20005",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "2000",
        "Price": "3",
        "PriceCurrency": "20001"
    },
    {
        "ID": "3",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20002",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "3000",
        "Price": "3",
        "PriceCurrency": "20001"
    },
    {
        "ID": "4",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20003",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "3000",
        "Price": "3",
        "PriceCurrency": "20001"
    },
    {
        "ID": "5",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20006",
        "LevelMin": "6",
        "LevelMax": "13",
        "Weight": "2000",
        "Price": "10",
        "PriceCurrency": "20001"
    },
    {
        "ID": "6",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20007",
        "LevelMin": "9",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "30",
        "PriceCurrency": "20001"
    },
    {
        "ID": "7",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "20008",
        "LevelMin": "14",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "100",
        "PriceCurrency": "20001"
    },
    {
        "ID": "8",
        "Slot": "2",
        "ItemType": "1",
        "RefID": "20004",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "2500",
        "Price": "8",
        "PriceCurrency": "20001"
    },
    {
        "ID": "9",
        "Slot": "2",
        "ItemType": "1",
        "RefID": "20005",
        "LevelMin": "1",
        "LevelMax": "8",
        "Weight": "2500",
        "Price": "5",
        "PriceCurrency": "20001"
    },
    {
        "ID": "10",
        "Slot": "2",
        "ItemType": "1",
        "RefID": "20006",
        "LevelMin": "6",
        "LevelMax": "13",
        "Weight": "2000",
        "Price": "15",
        "PriceCurrency": "20001"
    },
    {
        "ID": "11",
        "Slot": "2",
        "ItemType": "1",
        "RefID": "20007",
        "LevelMin": "9",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "50",
        "PriceCurrency": "20001"
    },
    {
        "ID": "12",
        "Slot": "2",
        "ItemType": "1",
        "RefID": "20008",
        "LevelMin": "14",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "150",
        "PriceCurrency": "20001"
    },
    {
        "ID": "13",
        "Slot": "2",
        "ItemType": "2",
        "RefID": "1",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "3000",
        "Price": "20",
        "PriceCurrency": "20001"
    },
    {
        "ID": "14",
        "Slot": "2",
        "ItemType": "2",
        "RefID": "2",
        "LevelMin": "6",
        "LevelMax": "13",
        "Weight": "2000",
        "Price": "80",
        "PriceCurrency": "20001"
    },
    {
        "ID": "15",
        "Slot": "2",
        "ItemType": "2",
        "RefID": "3",
        "LevelMin": "9",
        "LevelMax": "17",
        "Weight": "1500",
        "Price": "200",
        "PriceCurrency": "20001"
    },
    {
        "ID": "16",
        "Slot": "3",
        "ItemType": "2",
        "RefID": "1",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "3000",
        "Price": "25",
        "PriceCurrency": "20001"
    },
    {
        "ID": "17",
        "Slot": "3",
        "ItemType": "2",
        "RefID": "2",
        "LevelMin": "6",
        "LevelMax": "13",
        "Weight": "2500",
        "Price": "100",
        "PriceCurrency": "20001"
    },
    {
        "ID": "18",
        "Slot": "3",
        "ItemType": "2",
        "RefID": "3",
        "LevelMin": "9",
        "LevelMax": "17",
        "Weight": "2000",
        "Price": "250",
        "PriceCurrency": "20001"
    },
    {
        "ID": "19",
        "Slot": "3",
        "ItemType": "2",
        "RefID": "4",
        "LevelMin": "12",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "500",
        "PriceCurrency": "20001"
    },
    {
        "ID": "20",
        "Slot": "3",
        "ItemType": "2",
        "RefID": "5",
        "LevelMin": "14",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "1000",
        "PriceCurrency": "20009"
    },
    {
        "ID": "21",
        "Slot": "4",
        "ItemType": "2",
        "RefID": "1",
        "LevelMin": "1",
        "LevelMax": "5",
        "Weight": "3000",
        "Price": "30",
        "PriceCurrency": "20001"
    },
    {
        "ID": "22",
        "Slot": "4",
        "ItemType": "2",
        "RefID": "2",
        "LevelMin": "6",
        "LevelMax": "13",
        "Weight": "2500",
        "Price": "120",
        "PriceCurrency": "20001"
    },
    {
        "ID": "23",
        "Slot": "4",
        "ItemType": "2",
        "RefID": "3",
        "LevelMin": "9",
        "LevelMax": "17",
        "Weight": "2000",
        "Price": "300",
        "PriceCurrency": "20001"
    },
    {
        "ID": "24",
        "Slot": "4",
        "ItemType": "2",
        "RefID": "4",
        "LevelMin": "12",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "600",
        "PriceCurrency": "20001"
    },
    {
        "ID": "25",
        "Slot": "4",
        "ItemType": "2",
        "RefID": "5",
        "LevelMin": "14",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "2",
        "PriceCurrency": "20009"
    },
    {
        "ID": "27",
        "Slot": "5",
        "ItemType": "1",
        "RefID": "20009",
        "LevelMin": "6",
        "LevelMax": "13",
        "Weight": "2000",
        "Price": "500",
        "PriceCurrency": "20001"
    },
    {
        "ID": "28",
        "Slot": "5",
        "ItemType": "1",
        "RefID": "20010",
        "LevelMin": "9",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "500",
        "PriceCurrency": "20009"
    },
    {
        "ID": "29",
        "Slot": "5",
        "ItemType": "1",
        "RefID": "20011",
        "LevelMin": "14",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "500",
        "PriceCurrency": "20010"
    },
    {
        "ID": "30",
        "Slot": "5",
        "ItemType": "1",
        "RefID": "20004",
        "LevelMin": "1",
        "LevelMax": "8",
        "Weight": "3000",
        "Price": "3",
        "PriceCurrency": "20001"
    },
    {
        "ID": "31",
        "Slot": "5",
        "ItemType": "1",
        "RefID": "20005",
        "LevelMin": "3",
        "LevelMax": "13",
        "Weight": "2500",
        "Price": "8",
        "PriceCurrency": "20001"
    },
    {
        "ID": "32",
        "Slot": "5",
        "ItemType": "1",
        "RefID": "20006",
        "LevelMin": "6",
        "LevelMax": "17",
        "Weight": "2000",
        "Price": "25",
        "PriceCurrency": "20001"
    },
    {
        "ID": "33",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20002",
        "LevelMin": "1",
        "LevelMax": "42",
        "Weight": "3000",
        "Price": "5",
        "PriceCurrency": "20001"
    },
    {
        "ID": "34",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20003",
        "LevelMin": "1",
        "LevelMax": "42",
        "Weight": "3000",
        "Price": "5",
        "PriceCurrency": "20001"
    },
    {
        "ID": "35",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20004",
        "LevelMin": "1",
        "LevelMax": "8",
        "Weight": "2500",
        "Price": "8",
        "PriceCurrency": "20001"
    },
    {
        "ID": "36",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20005",
        "LevelMin": "3",
        "LevelMax": "13",
        "Weight": "2000",
        "Price": "15",
        "PriceCurrency": "20001"
    },
    {
        "ID": "37",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20006",
        "LevelMin": "6",
        "LevelMax": "17",
        "Weight": "2000",
        "Price": "40",
        "PriceCurrency": "20001"
    },
    {
        "ID": "38",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20007",
        "LevelMin": "9",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "80",
        "PriceCurrency": "20001"
    },
    {
        "ID": "39",
        "Slot": "6",
        "ItemType": "1",
        "RefID": "20008",
        "LevelMin": "14",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "200",
        "PriceCurrency": "20009"
    },
    {
        "ID": "40",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "30011",
        "LevelMin": "1",
        "LevelMax": "42",
        "Weight": "2500",
        "Price": "5",
        "PriceCurrency": "20001"
    },
    {
        "ID": "41",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "30012",
        "LevelMin": "3",
        "LevelMax": "42",
        "Weight": "1500",
        "Price": "15",
        "PriceCurrency": "20001"
    },
    {
        "ID": "42",
        "Slot": "1",
        "ItemType": "1",
        "RefID": "30013",
        "LevelMin": "6",
        "LevelMax": "42",
        "Weight": "800",
        "Price": "40",
        "PriceCurrency": "20001"
    }
];

module.exports = SHOP_DATA;
